apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-master
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  redis-master
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 75
      type: Resource
